application: hinkapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes



handlers:
- url: /favicon\.ico
  static_files: web/static/favicon.ico
  upload: favicon\.ico
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /fonts
  static_dir: static/fonts
- url: /static
  static_dir: web/static
  # Endpoints handler: Must be /_ah/spi. Apps send requests to /_ah/api, but these are handled at /_ah/spi!!
- url: /_ah/spi/.*
  script: hink_api.APPLICATION
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
